#!/usr/bin/env python3
import subprocess
import json

# load history from ~/.same
f_name = os.path.join(os.path.join(os.path.expanduser('~'), '.same'))

with open(f_name, 'r') as f:
    hist = json.loads(f.read())

    for inp in hist:
        print('tbh $ ' + inp)
        subprocess.call(inp)

    print('gottem')

