#!/usr/bin/env python3
import json
import os

hist = []
inp = input('tbh (recording) $ ')

while not inp == 'donezo':
    os.system(inp)
    hist.append(inp)
    inp = input('tbh (recording) $ ')

# save hist to ~/.same
f_name = os.path.join(os.path.join(os.path.expanduser('~'), '.same'))
with open(f_name, 'w') as f:
    f.write(json.dumps(hist))

print('gottem')

