#!/usr/bin/env python3
import argparse
import json
import sys
import os

F_NAME = os.path.join(os.path.join(os.path.expanduser('~'), '.same'))


def load():
    """Load history from ~/.same"""
    try:
        with open(F_NAME, 'r') as f:
            return json.loads(f.read())
    except FileNotFoundError:
        return {}

def execute(commands):
    """Execute a list of bash commands."""
    if not commands: 
        print('nothing to same')
        return

    for inp in commands:
        print('same $ ' + inp)
        os.system(inp)

    print('gottem')

def record():
    """Record a list of bash command."""
    hist = []
    inp = input('tbh (recording) $ ')

    while not inp == 'donezo':
        os.system(inp)
        hist.append(inp)
        inp = input('tbh (recording) $ ')

    return hist

def save(commands, macro='dude'):
    """Save commands to ~/.same"""
    if not commands: return

    hist = load()
    hist[macro] = commands

    with open(F_NAME, 'w') as f:
        f.write(json.dumps(hist))
    
    print('gottem')

def delete(macro='dude'):
    hist = load()
    
    if macro not in hist:
        print('macro not found')
        return

    del hist[macro]

    with open(F_NAME, 'w') as f:
        f.write(json.dumps(hist))

    print(macro + ' got rekt')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Record and execute bash macros.")
    subparsers = parser.add_subparsers(help="sucommand help", dest='command')

    default_parser = subparsers.add_parser('record',
            description="Default command. Record series of bash commands",
            help='Default command. record help')
    default_parser.add_argument('macro', help='The macro to modify', nargs='?', default='dude')

    fuk_parser = subparsers.add_parser('fuk',
            description="Delete a macro",
            help='fuk help')
    fuk_parser.add_argument('macro', help='The macro to modify', nargs='?', default='dude')

    same_parser = subparsers.add_parser('same',
            description="Execute a saved macro",
            help='same help')
    same_parser.add_argument('macro', help='The macro to modify', nargs='?', default='dude')

    if len(sys.argv) == 1 or sys.argv[1] not in ['record', 'fuk', 'same']:
        args = parser.parse_args(['record'] + sys.argv[1:])
    else:
        args = parser.parse_args()

    if args.command == 'record':
        save(record(), macro=args.macro)
    elif args.command == 'same':
        execute(load()[args.macro])
    elif args.command == 'fuk':
        delete(args.macro)
